### PR TITLE
Check if remote library url exists

### PR DESCRIPTION
**Pull request by HesyRa**
https://github.com/jsdelivr/jsdelivr-wordpress/issues/11

### CODE REVIEW

**Comment by HesyRa** [comment]
[Update footer info](https://trello.com/c/mjOq2SVs/935-update-footer-info)

**Comment by HesyRa** [comment]
[jsdelivr-plugin issue #11](https://trello.com/c/gAJMpSag/934-jsdelivr-plugin-issue-11)

**Comment by MartinKolarik** [comment]
Let's check the file contents rather than status code. Also increase timeout to 30 seconds.

**Comment by HesyRa** [comment]
@MartinKolarik you mean use `file_get_contents` ? But this is much longer to check for url existans. You want to compare it with original file?

**Comment by MartinKolarik** [comment]
Or `wp_safe_remote_get()`, yes.

**Comment by HesyRa** [comment]
@MartinKolarik thnx. Have ideas to update code in right way, will finish tomorrow.

**Comment by HesyRa** [comment]
@MartinKolarik morning, please check updated.

**Comment by MartinKolarik** [comment]
LGTM.

**Pull request merged**
