### PR TITLE
Respect WP coding standarts

### PR DESCRIPTION
**Pull request by HesyRa**
https://github.com/jsdelivr/jsdelivr-wordpress/issues/17

### CODE REVIEW

**Comment by HesyRa** [comment]
[jsdelivr-plugin issue #17](https://trello.com/c/OHjnplJc/942-jsdelivr-plugin-issue-17)

**Comment by HesyRa** [comment]
@MartinKolarik code style updated, please check when you have time. (whould be hard to work on other task until this one is merged). Thnx.
Also I used different methods for remote and local files to actualy fit standarts (method file_get_contents not allowed)
```
if ( strpos( $source[ self::ORIGINAL_SOURCE_URL ], '//' ) !== false ) {
			$response = wp_safe_remote_get( $source[ self::ORIGINAL_SOURCE_URL ] );

			$file_content = wp_remote_retrieve_body( $response );
		} else {
			$file_content = $wp_filesystem->get_contents( $source[ self::ORIGINAL_SOURCE_URL ] );
		}
```

**Comment by HesyRa** [comment]
@MartinKolarik today I've made lot of changes at this PR, because found bugs etc. All changes described at  push comment. Please take a look. Thnx.

**Comment by MartinKolarik** [comment]
@HesyRa not sure if you've seen it but I also left you two review comments yesterday.

**Comment by HesyRa** [comment]
@MartinKolarik no I don't where are they?

**Comment by MartinKolarik** [comment]
My bad, I didn't realize I need to submit the review as a whole too after submitting individual comments. You should be able to see it now.

**Comment by HesyRa** [comment]
@MartinKolarik Yes I see know. Will update code tomorrow. Thnx

**Comment by HesyRa** [comment]
@MartinKolarik code updated, please take a look. Mostly I'm worried about frontend changes I've done without any discussion. ^_^

**Comment by HesyRa** [comment]
https://github.com/jsdelivr/jsdelivr-wordpress/issues/18 Merged here.

**Comment by HesyRa** [comment]
https://github.com/jsdelivr/jsdelivr-wordpress/issues/15 Merged here

**Comment by MartinKolarik** [comment]
@HesyRa I'll check everything tomorrow.

**Comment by HesyRa** [comment]
@MartinKolarik I'm sry for that, fixed.

**Comment by MartinKolarik** [comment]
No error now but it still doesn't work. Unselect something and after refresh it's selected again.

**Comment by MartinKolarik** [comment]
@HesyRa Unselect All -> Save

**Comment by HesyRa** [comment]
@MartinKolarik Fixed. Done regress test. Everything worked localy.

**Pull request merged**
